language: node_js

node_js:
    - 4.6
    - 6.9
    - 7.1

cache:
    directories:
        - node_modules

script:
    - npm test
    - node ./tools/travis-commit-message-checker.js

after_success:
    - bash <(curl -s https://codecov.io/bash)
